version: "3.8"

services:
  localstack:
    container_name: localstack-dwhi
    image: localstack/localstack:3.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-southeast-2
      - DYNAMODB_REMOVE_EXPIRED_ITEMS=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "./localstack-init:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
