name: Deploy DWHI Backend Artifacts

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: "8.0.x"
  S3_KEY: ${{ vars.PIPELINE_BACKEND_KEY }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # restore dependencies for tests project only as it has a project reference to the app project
      - name: Restore dependencies
        run: dotnet restore backend/DoWeHaveItApp.Tests/DoWeHaveItApp.Tests.csproj

      # skip integration test
      - name: Run DoWeHaveItApp.Tests
        run: dotnet test backend/DoWeHaveItApp.Tests/DoWeHaveItApp.Tests.csproj -c Release --no-restore --filter "FullyQualifiedName!~Integration"

      - name: Publish DWHI App
        run: dotnet publish backend/DoWeHaveItApp/DoWeHaveItApp.csproj -c Release -o backend/DoWeHaveItApp/bin/lambda-publish --no-restore

      # package published artifact into a zip file
      - name: Package backend source
        run: zip -r ${{ env.S3_KEY }} backend/DoWeHaveItApp/bin/lambda-publish

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload package to S3
        run: aws s3 cp ${{ env.S3_KEY }} s3://${{ vars.PIPELINE_SOURCE_BUCKET }}/${{ env.S3_KEY }}
